service: webp-node

plugins:
  - serverless-offline
  - serverless-apigw-binary
  - serverless-api-cloudfront

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: us-east-1

custom:
  apigwBinary:
    types:
      - 'image/*'

  apiCloudFront:
    compress: true
    cookies: none
    querystring: none

package:
  exclude:
    - test/**
    - .idea/**
    - serverless.yml

functions:
  webp:
    handler: handler.cwebp
    timeout: 30
    memorySize: 1280
    events:
      - http: get /webp
      - http: get /webp/{proxy+}
  jp2:
    handler: handler.im
    timeout: 30
    memorySize: 1536
    events:
      - http: get /jp2
      - http: get /jp2/{proxy+}
